### ISSUE TITLE
Wrap behavior / css mixins

### ISSUE THREAD

**Issue by davidsteinberger** [predixdesignsystem/px-tabs#15]
## Expected behavior and actual behavior:

This is rather a feature-request than a bug. It would be nice to be able to customize the *wrap-behavior*. We have many tabs and I'd rather have them wrap into 2 lines if the horizontal space is constraint. 

Could a css-mixin be added to `.tabs-container__nav` that allows to customize this (I'd be happy to send a PR)?

## Steps to reproduce the problem:

Add many tabs to `px-tabs` and have them render titles that can not be wrapped.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

- px-tabs@2.1.1

## Code example

https://glitch.com/edit/#!/lightning-resolution

**Comment by davidsteinberger** [comment]
@mdwragg ping

**Comment by mdwragg** [comment]
Hi, sadly we all got laid off last week. Support will be limited until there is a plan out in place to figure out how to support the design system.

**Comment by randyaskin** [comment]
Added in v2.1.2.
