### ISSUE TITLE
tab generating dynamically having issues

### ISSUE THREAD

**Issue by nraafee** [predixdesignsystem/px-tabs#16]
This is my code i am trying to repeat the tab title and tab content dynamically but it is not updating properly can you please guide me how to implement.

<dom-module id="pd-tab">
  <template>
    <div>
      <template is="dom-repeat" items="{{_getFilterData(filterData)}}" as="item">
        <px-tabs selected="2">
            <px-tab
              id='tab{{index}}'>{{item.Name}}
            </px-tab>
        </px-tabs>
        <iron-pages selected="2">
          <div id="tab1-content">
           tab1 content
          </div>
          <div id="tab2-content"><p>sub2-content</p></div>
          <div id="tab3-content"><p>sub2-content</p></div>
          <div id="tab4-content"><p>subb4-content"</p></div>
        </iron-pages>
      </template>
    </div>
  </template>

  <script>
    Polymer({
      is: 'pd-tab',
      properties: {
        filterData: {
          type: Array,
          value: function() {
            return [];
          }
        }
      },
      _getFilterData: function() {
        return _.isArray(this.filterData) ? this.filterData : [];
      }
    })
  </script>
</dom-module>

Regards,
Raafee N

**Comment by nraafee** [comment]
<px-tabs selected="2">
      <template is="dom-repeat" items="{{_getFilterData(filterData)}}" as="item">

            <px-tab
              id='tab{{index}}'>{{item.Name}}
            </px-tab>

        <iron-pages selected="2">
          <div id="tab1-content">
            <p>The Bengal tiger is found primarily in India with smaller populations in Bangladesh, Nepal, Bhutan, China and Myanmar. It is the most
              numerous of all tiger subspecies with more than 2,500 left in the wild. The creation of India’s tiger reserves in the 1970s helped to
              stabilize numbers, but poaching to meet a growing demand from Asia in recent years has once again put the Bengal tiger at risk. The mangroves
              of the Sundarbans—shared between Bangladesh and India—are the only mangrove forests where tigers are found. The Sundarbans are increasingly
              threatened by sea level rise as a result of climate change.</p>
          </div>
          <div id="tab2-content"><p>The black spider monkey—also known as the Guiana or red-faced spider monkey—is found in eastern South America in areas north of the Amazon River. They are one of seven species of spider monkeys found in Latin America and one of the largest primate species in South America.</p></div>
          <div id="tab3-content"><p>Sumatran elephants feed on a variety of plants and deposit seeds wherever they go, contributing to a healthy forest ecosystem. They also share their lush forest habitat with several other endangered species, such as the Sumatran rhino, tiger, and orangutan, and countless other species that all benefit from an elephant population that thrives in a healthy habitat.</p></div>
          <div id="tab4-content"><p>Dolphins are one of the oldest creatures in the world along with some species of turtles, crocodiles and sharks. The Ganges river dolphin was officially discovered in 1801. Ganges river dolphins once lived in the Ganges-Brahmaputra-Meghna and Karnaphuli-Sangu river systems of Nepal, India, and Bangladesh. But the species is extinct from most of its early distribution ranges.</p></div>
        </iron-pages>
      </template>
    </div>
  </template>
  </px-tabs>

its working now with the above changes

**Comment by nraafee** [comment]
now we are facing the which tab content is map to which tab because it is default it is expanded everything.

**Comment by randyaskin** [comment]
If everything is showing up on the page at once, you likely forgot to import `iron-pages`

**Comment by nraafee** [comment]
thanks for your reply randyaskin i have imported the iron-pages but still it is having issue.
everything is showing up on the page at once.

**Comment by nraafee** [comment]
as per the readme i did bower install px-tabs --save and find the below screen shot after installing the polymer 1.9 got updated but whole application blowned up nothing is working in the page

**Comment by randyaskin** [comment]
Because you're using px-data-table still, which will not be upgraded to Polymer 2, you should remain on Polymer 1.x.x and webcomponents 0.7.x - otherwise everything in your application absolutely will blow up.

**Comment by nraafee** [comment]
please help me out in fixing the px-tabs i deleted the bower components folder and freshly installed the bower_components
